// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ObjectConfig.Data;

namespace ObjectConfig.Migrations
{
    [DbContext(typeof(ObjectConfigContext))]
    [Migration("20191229135608_Create")]
    partial class Create
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ObjectConfig.Data.Application", b =>
                {
                    b.Property<Guid>("ApplicationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(64)")
                        .HasMaxLength(64);

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(512)")
                        .HasMaxLength(512);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(128)")
                        .HasMaxLength(128);

                    b.HasKey("ApplicationId");

                    b.ToTable("Applications");
                });

            modelBuilder.Entity("ObjectConfig.Data.Config", b =>
                {
                    b.Property<Guid>("ConfigId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(128)")
                        .HasMaxLength(128);

                    b.Property<DateTimeOffset>("DateFrom")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("DateTo")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(512)")
                        .HasMaxLength(512);

                    b.Property<Guid?>("EnvironmentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("VersionFrom")
                        .IsRequired()
                        .HasColumnType("nvarchar(23)")
                        .HasMaxLength(23);

                    b.Property<string>("VersionTo")
                        .HasColumnType("nvarchar(23)")
                        .HasMaxLength(23);

                    b.HasKey("ConfigId");

                    b.HasIndex("EnvironmentId");

                    b.ToTable("Configs");
                });

            modelBuilder.Entity("ObjectConfig.Data.ConfigElement", b =>
                {
                    b.Property<Guid>("ConfigElementId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ConfigId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ParrentConfigElementId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("TypeElementId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ConfigElementId");

                    b.HasIndex("ConfigId");

                    b.HasIndex("ParrentConfigElementId");

                    b.HasIndex("TypeElementId");

                    b.ToTable("ConfigElements");
                });

            modelBuilder.Entity("ObjectConfig.Data.Environment", b =>
                {
                    b.Property<Guid>("EnvironmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ApplicationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(64)")
                        .HasMaxLength(64);

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(512)")
                        .HasMaxLength(512);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(128)")
                        .HasMaxLength(128);

                    b.HasKey("EnvironmentId");

                    b.HasIndex("ApplicationId");

                    b.ToTable("Environments");
                });

            modelBuilder.Entity("ObjectConfig.Data.TypeElement", b =>
                {
                    b.Property<Guid>("TypeElementId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(512)")
                        .HasMaxLength(512);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("TypeElementId");

                    b.ToTable("TypeElements");
                });

            modelBuilder.Entity("ObjectConfig.Data.User", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsGlobalAdmin")
                        .HasColumnType("bit");

                    b.HasKey("UserId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            UserId = new Guid("0c167938-24b6-45a2-9558-12a512facdb9"),
                            DisplayName = "GlobalAdmin",
                            Email = "admin@global.net",
                            ExternalId = "b7c0bf50-9c73-4fb1-bdf2-ff680102bcb5",
                            IsGlobalAdmin = true
                        });
                });

            modelBuilder.Entity("ObjectConfig.Data.UsersApplications", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ApplicationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AccessRole")
                        .HasColumnType("int");

                    b.HasKey("UserId", "ApplicationId");

                    b.HasIndex("ApplicationId");

                    b.ToTable("UsersApplications");
                });

            modelBuilder.Entity("ObjectConfig.Data.UsersEnvironments", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("EnvironmentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AccessRole")
                        .HasColumnType("int");

                    b.HasKey("UserId", "EnvironmentId");

                    b.HasIndex("EnvironmentId");

                    b.ToTable("UsersEnvironments");
                });

            modelBuilder.Entity("ObjectConfig.Data.UsersTypes", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ValueTypeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AccessRole")
                        .HasColumnType("int");

                    b.HasKey("UserId", "ValueTypeId");

                    b.HasIndex("ValueTypeId");

                    b.ToTable("UsersTypes");
                });

            modelBuilder.Entity("ObjectConfig.Data.ValueElement", b =>
                {
                    b.Property<Guid>("ValueElementId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ChangeOwnerUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ConfigElementId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("DateFrom")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("DateTo")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid?>("TypeElementId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasMaxLength(2147483647);

                    b.HasKey("ValueElementId");

                    b.HasIndex("ChangeOwnerUserId");

                    b.HasIndex("ConfigElementId");

                    b.HasIndex("TypeElementId");

                    b.ToTable("ValueElements");
                });

            modelBuilder.Entity("ObjectConfig.Data.Config", b =>
                {
                    b.HasOne("ObjectConfig.Data.Environment", "Environment")
                        .WithMany("Configs")
                        .HasForeignKey("EnvironmentId");
                });

            modelBuilder.Entity("ObjectConfig.Data.ConfigElement", b =>
                {
                    b.HasOne("ObjectConfig.Data.Config", "Config")
                        .WithMany("Configs")
                        .HasForeignKey("ConfigId");

                    b.HasOne("ObjectConfig.Data.ConfigElement", "Parrent")
                        .WithMany("Childs")
                        .HasForeignKey("ParrentConfigElementId");

                    b.HasOne("ObjectConfig.Data.TypeElement", "Type")
                        .WithMany()
                        .HasForeignKey("TypeElementId");
                });

            modelBuilder.Entity("ObjectConfig.Data.Environment", b =>
                {
                    b.HasOne("ObjectConfig.Data.Application", "Application")
                        .WithMany("Environments")
                        .HasForeignKey("ApplicationId");
                });

            modelBuilder.Entity("ObjectConfig.Data.UsersApplications", b =>
                {
                    b.HasOne("ObjectConfig.Data.Application", "Application")
                        .WithMany("Users")
                        .HasForeignKey("ApplicationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ObjectConfig.Data.User", "User")
                        .WithMany("Applications")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ObjectConfig.Data.UsersEnvironments", b =>
                {
                    b.HasOne("ObjectConfig.Data.Environment", "Environment")
                        .WithMany("Users")
                        .HasForeignKey("EnvironmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ObjectConfig.Data.User", "User")
                        .WithMany("Environments")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ObjectConfig.Data.UsersTypes", b =>
                {
                    b.HasOne("ObjectConfig.Data.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ObjectConfig.Data.TypeElement", "ValueType")
                        .WithMany()
                        .HasForeignKey("ValueTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ObjectConfig.Data.ValueElement", b =>
                {
                    b.HasOne("ObjectConfig.Data.User", "ChangeOwner")
                        .WithMany()
                        .HasForeignKey("ChangeOwnerUserId");

                    b.HasOne("ObjectConfig.Data.ConfigElement", null)
                        .WithMany("Value")
                        .HasForeignKey("ConfigElementId");

                    b.HasOne("ObjectConfig.Data.TypeElement", "Type")
                        .WithMany()
                        .HasForeignKey("TypeElementId");
                });
#pragma warning restore 612, 618
        }
    }
}
